include:
  - ./superbase/docker/docker-compose.yml

services:
  api:
    container_name: "travelroot_backend"
    #    restart: always
    environment:
      ENVIRONMENT: development
    build:
      context: ./api
      dockerfile: dockerfile
    volumes:
      - "./api:/opt/app/api"
    #ports:
    #  - "3333:8080"
    expose:
      - 3333
    depends_on:
      - rest
    # networks:
    #     - db
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.travelroot-api.rule=Host(`travelroot.baptistegrimaldi.com`) && PathPrefix(`/main`)"
      - "traefik.http.routers.travelroot-api.priority=20"
      - "traefik.http.routers.travelroot-api.entrypoints=web-secured"
      - "traefik.http.routers.travelroot-api.tls=true"
      - "traefik.http.routers.travelroot-api.tls.certresolver=grimresolver"
      - "traefik.http.routers.travelroot-api.middlewares=strip-api"
      - "traefik.http.services.trinity-api.loadbalancer.server.port=3333"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/main"

networks:
  web:
    external: true
