include:
  - ./supabase/docker/docker-compose.yml

services:
  api:
    container_name: "travelroot_backend"
    #    restart: always
    environment:
      ENVIRONMENT: development
    build:
      context: ./api
      dockerfile: dockerfile
    volumes:
      - "./api:/opt/app/api"
    #ports:
    #  - "3333:8080"
    expose:
      - 3333
    depends_on:
      - rest
    # networks:
    #     - db
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.travelroot-web.rule=Host(`travelroot-box.baptistegrimaldi.com`)"
      - "traefik.http.routers.travelroot-web.entrypoints=web"
      - "traefik.http.routers.travelroot-web.middlewares=redirect@file"
      - "traefik.http.routers.travelroot-web-secured.rule=Host(`travelroot-box.baptistegrimaldi.com`)"
      - "traefik.http.routers.travelroot-web-secured.entrypoints=web-secured"
      - "traefik.http.routers.travelroot-web-secured.tls.certresolver=grimresolver"
      - "traefik.http.services.travelroot-web-secured.loadbalancer.server.port=3333"
networks:
  web:
    external: true
