FROM golang:1.24

WORKDIR /opt/app/api

# go.mod et go.sum pour télécharger les dépendances
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# air pour le développement
RUN go install github.com/air-verse/air@latest

COPY . .

# Construir l'application
# RUN go build -o build ./main.go

CMD ["air", "-c", ".air.toml"]
